version: '3'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile-test
    environment:
    - PORT=8000
    - DBSERVICE=postgres
    - DBNAME=addb
    - DBUSER=addb
    - DBPASSWD=addb
    - DBHOST=db
    - DBPORT=5432
    - DBDEBUG=false
    - REDISURL=cache:6379
    - DEBUG=true
    ports:
    - 8000:8000
    depends_on:
    - db
    - cache
    networks:
      default:
      internal:
  db:
    image: postgres:latest
    environment:
    - POSTGRES_USER=addb
    - POSTGRES_PASSWORD=addb
    - POSTGRES_DB=addb
    networks:
      internal:
  cache:
    image: redis:latest
    networks:
      internal:


networks:
  default:
  internal:
    internal: true
