version: '3'

services:
  api:
    build: .
    user: api
    environment:
    - PORT=8000
    - DBSERVICE=mysql
    - DBNAME=addb
    - DBUSER=addb
    - DBPASSWD=addb
    - DBHOST=db
    - DBPORT=3306
    - REDISURL=cache:6379
    ports:
    - 8000:8000
    depends_on:
    - db
    - cache
    entrypoint: "bash -c 'sleep 5 && ./DcardBackendIntern2024'"
    networks:
      default:
      internal:
  db:
    image: mariadb:latest
    environment:
    - MYSQL_ROOT_PASSWORD=addb
    - MYSQL_USER=addb
    - MYSQL_PASSWORD=addb
    - MYSQL_DATABASE=addb
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      internal:
  cache:
    image: redis:latest
    networks:
      internal:


networks:
  default:
  internal:
    internal: true

volumes:
  mysql-data:
