name: Unit test

on:
  push:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # need checkout before using docker-compose-action
    - uses: actions/checkout@v3
    - uses: adambirds/docker-compose-action@v1.3.0
      with:
        compose-file: "./docker-compose-test.yml"
        down-flags: "--volumes"
        services: |
          db
          cache
        test-container: api
        test-command: "bash -c 'sleep 5 && make test'"


